### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by hfiguiere** [flathub/net.werwolv.ImHex#8]
The build is broken because the runtime was changed to a version that do not exist.

**Comment by WerWolv** [comment]
Hey, yeah I noticed. But the build also didn't work before because ImHex requires GCC 12.1.0 for building which apparently isn't available on the build server right now

**Comment by hfiguiere** [comment]
But the build would not be broken had you waited for the build to finish (and fail) before closing the PR after doing random changes.

**Comment by WerWolv** [comment]
Reverted it back now. Still need to check how to get gcc 12 setup. I guess I need to compile it myself in the build script?
